'''b=bool(True)
print("The datatype of b is:",type(b))
b=int(b)
print("Now the datatype of b is:",type(b))

c=bool(False)
print("The datatype of c is:",type(c))
c=float(c)
print("Now the datatype of c is:",type(c))'''

'''d=bool(False)
print("The datatype of d is:",type(d))
d=int(d)
print("Now the datatype of d is",type(d))
d=float(d)
print("Now the datatype of d is",type(d))
d=bool(d)
print("Now the datatype of d is",type(d))
d=float(d)
print("Now the datatype of d is",type(d))
d=str(d)
print("Now the datatype of d is",type(d))
d=bool(d)
print("Now the datatype of d is",type(d))
print("")'''

e= bool(input(" Enter true or false:"))
print("Datatype of e is:",type(e))
e=str(e)
print("Now datatype of e is:",type(e))
e=int(e)
print("Datatype of e is:",type(e))
e=float(e)
print("Datatype of e is:",type(e))

e=bool(e)
print("Datatype of e is:",type(e))
e=float(e)
print("Datatype of e is:",type(e))
e=str(e)
print("Datatype of e is:",type(e))
e=bool(e)
print("Datatype of e is:",type(e))